### ISSUE TITLE
Rewrite to be simpler to new content

### ISSUE THREAD

**Issue by Xon** [Xon/XenForo2-TitleEditHistory#3]
Currently each content type supported effectively has the same code copy & pasted between various places. Traits would reduce the code duplication

**Comment by ticktackk** [comment]
PR: https://github.com/Xon/XenForo2-TitleEditHistory/pull/4

**Comment by Xon** [comment]
@ticktackk I've started the conversation support but I ran into issues where I really need a bunch of infrastructure from Conversation Improvements for it to make sense

**Comment by ticktackk** [comment]
I figured after reading https://xenforo.com/community/threads/conversation-editing-should-use-service-framework.144900/

**Comment by Xon** [comment]
I think this is fairly close to being 'done', might see if this makes sense to support XFMG bits

**Comment by ticktackk** [comment]
I think adding support for album title would be better instead of media title.
